# Generated by Django 5.1.2 on 2024-10-25 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='material',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='material_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sklad.material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='remainder',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.material')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.product')),
            ],
        ),
    ]
