# Generated by Django 5.1.2 on 2024-10-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0003_order_shirt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
