# Generated by Django 5.1.2 on 2024-10-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0005_remove_product_materials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shirt',
        ),
    ]
