# Generated by Django 5.1.2 on 2024-10-29 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0006_delete_shirt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('productmaterial_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sklad.productmaterial')),
                ('fabric_required', models.FloatField(default=0.8)),
                ('buttons_required', models.IntegerField(default=5)),
                ('thread_required', models.FloatField(default=10)),
            ],
            bases=('sklad.productmaterial', models.Model),
        ),
    ]
